### ISSUE TITLE
Document embedLanguages build task

### ISSUE THREAD

**Issue by wyantb** [moment/momentjs.com#130]
Inspired by https://github.com/moment/moment/pull/1057 and an update to Grunt (?) that seems to have broken auto-resolving (?) the difference between `--embed_languages` and `--embedLanguages`.

**Comment by rjruizes** [comment]
`embedLocales` is deprecated; use `transpile`
Example: `grunt transpile:fr,ru` to generate _moment-with-locales.custom.js_ with French and Russian.

**Comment by JobaDiniz** [comment]
Hi, I forked the latest version and I'm trying to build with custom languages (version 2.10.3), but got:

```
$ grunt transpile:hu
Running "transpile:hu" (transpile) task

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "transpile-raw" task
>> build/umd/moment.js
>> build/umd/locale/*.js
>> build/umd/test/moment/*.js
>> error transpiling [Error: Module 'C:/Users/Joberto/Projetos/Forks/moment/src/moment' does not exp
ort 'moment' (imported by 'test/locale/de-at')]
Warning: Module 'C:/Users/Joberto/Projetos/Forks/moment/src/moment' does not export 'moment' (import
ed by 'test/locale/de-at') Use --force to continue.
```

**Comment by rjruizes** [comment]
@JobaDiniz See https://github.com/moment/moment/pull/2376

**Comment by JobaDiniz** [comment]
Thanks

**Comment by marwahaha** [comment]
Is this still open?

**Comment by marwahaha** [comment]
Closing due to age --and there's information about [transpile here](http://momentjs.com/docs/#/i18n/loading-into-browser/).
