### ISSUE TITLE
moment.duration(0).humanize() == 'a few seconds'

### ISSUE THREAD

**Issue by acicali** [moment/momentjs.com#157]
As the subject states, calling moment.duration(0).humanize() returns the text "a few seconds". I'm building a tiny stopwatch component where I don't actually want to display the timer, just the total difference of time. Upon loading, the timer already states "a few seconds".  I realize I could easily handle this case, but humanize() might be just one tick better if it accurately handled duration(0).

I'm not exactly sure what a better response would be for duration(0). Maybe just return an empty string? For humanize(true), probably "just now" would be good. I hope this doesn't sound like nitpicking, momentjs is awesome! Keep up the good work!

Thanks for reading.

**Comment by mj1856** [comment]
Sorry this item has been festering, but if it's still a concern, then please log to https://github.com/moment/moment/issues instead of here.  Thanks.
