### ISSUE TITLE
Can't copy text on moment homepage

### ISSUE THREAD

**Issue by icambron** [moment/momentjs.com#158]
Some users are reporting that their selections are cleared or modified by the clock tick on the home page. Here's the issue filed in the main repo: https://github.com/moment/moment/issues/1982

**Comment by mj1856** [comment]
I don't think this is an issue anymore.

**Comment by Offirmo** [comment]
Sorry, just checked on Chrome and FF latest, FF lose the selection and Chrome change it.

**Comment by mj1856** [comment]
Ok, I'll reopen.  I couldn't reproduce it in Chrome latest on Windows, but if you can then it should be investigated further.

Any chance of using a screen-recorder utility?  There are several that produce animated gifs that would be easy to post here.  Thanks.

**Comment by icambron** [comment]
FWIW, this reproduces simply enough for me on Firefox on my Mac.

**Comment by Starojitski** [comment]
Showing real time clock changes is a gimmick - serves no real purpose at best and in this case is counter productive for many
