### ISSUE TITLE
Documentation in "Changing locales locally" section seems to be incorrect

### ISSUE THREAD

**Issue by mattgrande** [moment/momentjs.com#167]
See [here](http://momentjs.com/docs/#/i18n/instance-locale/) on the live site.

    var fr = moment().locale('fr');
    fr.locale().months(moment([2012, 0])) // "janvier"

Running this in the console (Chrome 39.0.2171.95) returns `TypeError: undefined is not a function`, instead of the expected month name.

**Comment by radakovich** [comment]
This will be fixed when https://github.com/moment/momentjs.com/pull/181 is merged.
