### ISSUE TITLE
Revisit Australian time zone abbreviations

### ISSUE THREAD

**Issue by mj1856** [moment/momentjs.com#178]
In the [Formatting Additions section of the moment-timezone docs](http://momentjs.com/timezone/docs/#/using-timezones/formatting/), we talk about Australian time zone offsets.  There are a couple of issues:

- It was never "Eastern Saving Time", but rather "Eastern Summer Time".

- Due to updates in [tzdb 2014f](http://mm.icann.org/pipermail/tz-announce/2014-August/000023.html), moment now returns `AEST` and `AEDT`, which contradicts the sample.  It also makes it a moot point.

Should we perhaps just remove this paragraph?

**Comment by maggiepint** [comment]
Removed paragraph in PR #296 and updated abbreviation comparison to use America/Chicago and Asia/Shanghai
