### ISSUE TITLE
Time Zone Builder "Coming Soon"?

### ISSUE THREAD

**Issue by rtablada** [moment/momentjs.com#187]
I was looking to create a subset of the packaged timezone data (services only covering US/Canada or just EU), and found that the time zone data builder says "Coming Soon" http://momentjs.com/timezone/data/.

In needing this for a company project, I was able to create a small node.js project to accomplish this: https://damp-inlet-8848.herokuapp.com/

I wanted to see what the plan is for the future of the data builder for the site.
This is a fairly thin express app, but the current site is served by static files.

This could be done in the browser although it would require `encodeURI` browser support.

I'm looking for guidance to be able to create a possible PR.

**Comment by rtablada** [comment]
Hmm... The above app is currently broken.

tz.load looks for packed data and I'm sending unpacked...

Looking to fix this issue...

**Comment by mj1856** [comment]
Related moment/moment-timezone#9

**Comment by marwahaha** [comment]
Closing this, I guess it's still "Coming Soon"...
