### ISSUE TITLE
"L" format produces wrong output.

### ISSUE THREAD

**Issue by maxim-boligatov** [moment/momentjs.com#200]
Sample code:

    <script src="~/Scripts/moment-with-locales.js"></script>

    <script>
        var text = moment().format("L");
        document.write(text);
    </script>

OUTPUT:

2015年5月28日 

should be: 05/28/2015

Tested in last versions of Firefox, Chrome, Opera.

Reproduced in momentjs v2.10.3, last bug-free version is 2.9.0

**Comment by mj1856** [comment]
Same as moment/moment#2390 & moment/moment#2367
