### ISSUE TITLE
moment().format("Do") returns 14, not 14th as expected.

### ISSUE THREAD

**Issue by makrem025** [moment/momentjs.com#203]
moment("2010-02-14T08:02:17-05:00").format("Do") returns 14, but should return 14th as per the [documentation on format](http://momentjs.com/docs/#/displaying/format/).

Tested on version 2.10.3.

**Comment by mj1856** [comment]
I can't reproduce this.  It works as intended.

Here is a screenshot from Chrome debug console:

![image](https://cloud.githubusercontent.com/assets/1396388/8243010/4a77e994-15c8-11e5-8664-a62ef1363832.png)

If you can reproduce, open a new issue [here](https://github.com/moment/moment/issues).  This issue tracker is for the momentjs.com website, not the moment.js library.

Thanks.
