### ISSUE TITLE
Document add/subtract behavior when using days or greater.

### ISSUE THREAD

**Issue by mj1856** [moment/momentjs.com#205]
The `add` and `subtract` functions use time-math when working with hours or smaller, but use date-math when working with days or larger.

Among other things, this means one cannot add or subtract fractional amounts of days, months, or years.

This should be explained in the documentation.

See moment/moment#2430.

**Comment by maggiepint** [comment]
This is done with PR #273 
http://momentjs.com/guides/#/lib-concepts/date-time-math/

**Comment by mj1856** [comment]
:+1:
