### ISSUE TITLE
Sentence ends abruptly in moment#format documentation

### ISSUE THREAD

**Issue by cyranix** [moment/momentjs.com#209]
Just before the first table of format tokens, the phrase `There are a couple conventions used with the naming of the` occurs. Not sure where this thought was headed, but it seems to have been interrupted.

**Comment by mj1856** [comment]
@timrwood - Looks like [your commit](https://github.com/moment/momentjs.com/commit/e20245aba332e93d8627d7d04a19de4206c462ec#diff-6aadc692022189ba328d0974c21d6f92).  Not sure what you planned to write here.
