### ISSUE TITLE
Wrong API written in documentation

### ISSUE THREAD

**Issue by powershotman** [moment/momentjs.com#210]
"moment().calendar(referenceTime);" should be -----> "moment(referenceTime).calendar();"

**Comment by mj1856** [comment]
Actually, no, those are two very different things.

The reference time controls the output formatting.  For example:

![image](https://cloud.githubusercontent.com/assets/1396388/8346858/77dbf5da-1ab7-11e5-9c03-6b52bb072f6e.png)
