### ISSUE TITLE
Update .js file names for timezone downloads

### ISSUE THREAD

**Issue by TWiStErRob** [moment/momentjs.com#218]
In the download section: http://momentjs.com/timezone/

The titles say:
 * `moment-timezone-2010-2020.js`
 * `moment-timezone-2010-2020.min.js` 8.4k
 * `moment-timezone-all-years.js`
 * `moment-timezone-all-years.min.js` 24k

but they point to `moment-timezone-with-data-*.js` files.

**Comment by TWiStErRob** [comment]
Same with `moment+locales.js`

**Comment by mikescott8** [comment]
so is this still open? looks like dan-l committed changes for this issue, from his comments.

**Comment by maggiepint** [comment]
nope, should be closed

**Comment by TWiStErRob** [comment]
I don't think this is fully fixed. The commit I found was only doing it for the main website, and those previous commits look like they weren't merged or did modify gh-pages directly.

**Comment by TWiStErRob** [comment]
Notice the `master` in this commit:
![image](https://cloud.githubusercontent.com/assets/2906988/14989484/6707359c-1158-11e6-9d2d-d70e9aa50cda.png)
but these other ones llsted above @mikescott8's comment doesn't have a branch:
![image](https://cloud.githubusercontent.com/assets/2906988/14989501/7a7f8534-1158-11e6-9db2-efeab85c43c2.png)
