### ISSUE TITLE
Add docs for Tawian calendar plugin

### ISSUE THREAD

**Issue by mj1856** [moment/momentjs.com#231]
Per moment/moment#2586, @bradwoo8621 has created a plugin to support the Taiwanese calendar.
https://github.com/bradwoo8621/moment-taiwan

It should be added to the plugins list in the docs.

**Comment by bradwoo8621** [comment]
Hi mj1856,

I've upgraded the moment-taiwan to 0.0.4, and deployed it into npm. https://www.npmjs.com/package/moment-taiwan

thanks

**Comment by mj1856** [comment]
@bradwoo8621 - Feel free to send a PR to this repo.

**Comment by bradwoo8621** [comment]
thanks, created, :)

**Comment by maggiepint** [comment]
closing in favor of #302
