### ISSUE TITLE
Calendar documentation example

### ISSUE THREAD

**Issue by balrogthane** [moment/momentjs.com#232]
At http://momentjs.com/docs/#/displaying/calendar-time/ where the documentation gives an example of specifying calendar output formats, it should include usage of the sameElse key. This key is not at all intuitively named and if it were in the example it would be immediately accessible and obvious to anyone wondering what the "otherwise" key might be.

**Comment by mj1856** [comment]
+1.  This might have prevented the confusion in moment/moment#2647.

**Comment by mj1856** [comment]
Fixed in #240
