### ISSUE TITLE
Moment().add(invalid_parameter) does not throw error or warning, can be misleading

### ISSUE THREAD

**Issue by victorbadila** [moment/momentjs.com#233]
I have the following code, which works as expected:

```
var b = moment().add(10, 'minutes').format();
console.log(b);
```

However if I do something likethis, no error or warnings are thrown:

```
var b = moment().add('10 minutes').format();
console.log(b);
// or
var b = moment().add('a dog').format();
console.log(b);
```

I feel this is a bit confusing as I had a bug where I added `'10 minutes'` at a point and everything seemed to work well except for the final result in the whole chain. Also I don't feel it is very safe for working with dynamic arguments, imo.

**Comment by mj1856** [comment]
Sounds like a feature request.  This repo is for the momentjs.com website (documentation, etc.)  You probably want to request this here: https://github.com/moment/moment/issues
