### ISSUE TITLE
Docs: Fractional Seconds

### ISSUE THREAD

**Issue by xMartin** [moment/momentjs.com#247]
Docs say:
```
S	0..9    Tenths of a second
SS	0..99   Hundreds of a second
SSS	0..999  Thousandths of a second
```
But shouldn't that be
```
S	0..9      Tenths of a second
SS	00..99    Hundreds of a second
SSS	000..999  Thousandths of a second
```

**Comment by mj1856** [comment]
Actually, the number of `S` characters really only matters when parsing in strict mode.  Otherwise, *any* `S` character sequence is interpreted as fractions of a second.  The docs should be clearer about that.
