### ISSUE TITLE
Error in formatting moment

### ISSUE THREAD

**Issue by debopamsengupta** [moment/momentjs.com#253]
I have a moment object  ```a```
![image](https://cloud.githubusercontent.com/assets/9649659/11651482/fc4d9d7c-9dcb-11e5-904a-9b3856200de4.png)

On calling ```a.format('YYYYMMDD')``` , I get this 

```TypeError","stack":"TypeError: this.localeData(...).postformat is not a function```

**Comment by PareshSolankiMI** [comment]
I have same issue.

**Comment by skolsuper** [comment]
Same.

**Comment by PareshSolankiMI** [comment]
Try this
moment(a).format('YYYYMMDD')
