### ISSUE TITLE
Momentjs does not parse date with Chinese format

### ISSUE THREAD

**Issue by raajamalik** [moment/momentjs.com#255]
This is regarding an issue we are facing with Chinese date format. 
I used a format - yyyy'年'mm'月'dd'日' 
Date - any date

It gives me - 2015'年'12'月'24'日'  
but it should give me 2015年12月24日  - notice there are no single quotes in the date. I formatted using this format with java or other jqx formatting - it gives me correct result. 

Can you please see, what is to be done. Does moment work well with Chinese timezone.

**Comment by mj1856** [comment]
This repo is for the momentjs.com website.  If you have issues with moment itself, please use the issue tracker in the moment repo at http://github.com/moment/moment/issues

Thanks.
