### ISSUE TITLE
Clarify how to load locales with WebPack

### ISSUE THREAD

**Issue by mj1856** [moment/momentjs.com#269]
Update the [Loading locales in the browser](https://github.com/moment/momentjs.com/blob/master/docs/moment/06-i18n/04-loading-into-browser.md) section with the info from moment/moment#1435.

Thanks.

**Comment by craigstroman** [comment]
Hi,

Is this still open?  

If it is I Might be interested in taking it.

Thank you.

**Comment by maggiepint** [comment]
I don't think anybody has done it. And we always take documentation improvements, even if something is already covered. Go for it.

**Comment by craigstroman** [comment]
Great.  This would be my first contribution though. 

Should I just clone the repo to work on it?

**Comment by maggiepint** [comment]
You're going to want to fork it. Then, clone your fork. You don't have permissions to push to our main repo, but you will be able to push to your fork and then make a pull against our main branch. How you do your git workflow within your fork is up to you, but I personally usually make a branch for each new thing that I do. This way, my fork of master is clean and in line with the main master, not dirtied with commits that may or may not be merged to main.

If you need further help with this let me know.

**Comment by craigstroman** [comment]
Ok, thank you for the information.

**Comment by craigstroman** [comment]
Hi Maggie,

Sorry for the long delay since yesterday but I do still have a question since I got my local environment set.

I looked through issue 1435 but I don't really see anything talking about loading locale files in the browser.  

Could you please point me in the right direction?

**Comment by craigstroman** [comment]
Hi,

Does this still need to be done?

**Comment by ichernev** [comment]
@craigstroman yes, because : https://github.com/moment/moment/pull/3344

**Comment by Barkha54** [comment]
Hi, I'm new to open source projects. I tried running the script compile.sh and then started the server using **grunt server** command. In my command prompt it is showing **started connect web server on http //0.0.0.0:6060** but in the browser it is showing page cannot be displayed. Can someone please help me with this? 
![image](https://user-images.githubusercontent.com/24354626/31317383-97d43160-ac5d-11e7-8bb7-90821586f2ba.png)


![image](https://user-images.githubusercontent.com/24354626/31317390-c52ae00a-ac5d-11e7-8a6b-32172be32508.png)

**Comment by maggiepint** [comment]
Just use localhost:6060 instead

**Comment by Barkha54** [comment]
Thanks a lot. It worked.
