### ISSUE TITLE
Number of weeks between two moments?

### ISSUE THREAD

**Issue by martinkearn** [moment/momentjs.com#278]
Can I use Moment.js to calculate the number of weeks between two dates?

Specifically, I'm trying to work out the number of week between someone's birthday and the current date. I have the two dates as moments, but what next?

```
            //get todays date
            var today = moment()
            
            //get birth date
            var birthday = moment(year+"/"+month+"/"+day, 'YYYY-MM-DD');
```

The question I'm basically hoping to answer in my code is "how many weeks have I been alive"

**Comment by maggiepint** [comment]
You can use diff:
```js
today.diff(birthday, 'week')
```
More detailed documentation here:
http://momentjs.com/docs/#/displaying/difference/

**Comment by thiemeljiri** [comment]
How can I get the number of calendar weeks between two days? I mean the number of rows in calendar you would need to print the dates? This ignores the days in week and week numbers. Is there a clean and built in solution for that?

**Comment by mausam-varun** [comment]
g
