### ISSUE TITLE
Documentation typo for string formatting

### ISSUE THREAD

**Issue by avoliva** [moment/momentjs.com#280]
On the docs for string formatting, the format for `e` lists the output as `1..7`, though when using it comes out as `0..6`

**Comment by maggiepint** [comment]
I think you're maybe confusing ``e`` and ``E``.
Locale based day of week is ``e`` and should be 0-6.
ISO day of week is ``E`` and should be 1-7
See the following:

```js
moment('2016-03-20').format('e')
"0"
moment('2016-03-26').format('e')
"6"
moment('2016-03-21').format('E')
"1"
moment('2016-03-27').format('E')
"7"
```

**Comment by avoliva** [comment]
The documentation says `1..7` for both

**Comment by maggiepint** [comment]
AH, I follow you. You're referring to the parse documentation, but writing formatting code so I got somewhat confused. My bad. I am doing quite a few updates to docs. I'll get to it.

**Comment by maggiepint** [comment]
It is worth noting that we make no guarantees that the parse tokens (which you are looking at) are the same as the formatting tokens. If you're formatting, it is best to refer to the formatting token docs:
http://momentjs.com/docs/#/displaying/

**Comment by avoliva** [comment]
Ah yea, I thought I was looking at the docs for format, as that's what I was attempting to do. Sorry for the confusion.

**Comment by avoliva** [comment]
Same issue exists for `w ww` also, in the same section. Should count from 0
