### ISSUE TITLE
moment.js fails with "object is not extensible error"

### ISSUE THREAD

**Issue by fricke** [moment/momentjs.com#292]
Hello,

I'm getting this error consistently 

moment.js:2880 Uncaught TypeError: Can't add property _weekdaysParse, object is not extensible

within this block:
```
        if (!this._weekdaysParse) {
            this._weekdaysParse = [];
            this._minWeekdaysParse = [];
            this._shortWeekdaysParse = [];
            this._fullWeekdaysParse = [];
        }
```
When instantiating a moment.utc object like so:
```
moment.utc("Sat Mar 19 2016 12:00:00 +00:00", "ddd MMM DD YYYY hh:mm:ss Z")
```

What's very strange about this bug is that I'm only getting this when navigating to the particular page it's occurring on after the application, a single page application, has loaded.  Meaning, if I go directly to the page and moment loads up for the first time I don't receive the error.  When I'm on page2 and go to the page in question, I consistently get this error.  

It's very hard to trace where this is going wrong, but somehow 'this' is frozen at some point (although there's no immutability or Object.freeze code anywhere that I can currently find).  If I actually remove the date format, so moment.utc("Sat Mar 19 2016 12:00:00 +00:00"), I do not receive the error, but this gives me an invalid date in IE10/11.  

This error is simply not reproducible if you perform it via the console, node environment, only in our web application environment with the step detailed before.  So I know it's hard to comment on this, but what I am looking for is if there would be any clue with the immutability issue.  Would moment's 'this' object every be immutable?  

Currently, I'm on moment: 2.12.0 version and have updated today to 2.13.0 with no luck.  

Any help, suggestions, things to look at would be greatly appreciated.  This is currently becoming a blocker in using moment (although we've been using moment for a better part of a year now).  

Chris

**Comment by fricke** [comment]
2.7.0 doesn't have this issue, but 2.8.1 has a variant of this issue w/
![screen shot 2016-04-18 at 2 42 09 pm](https://cloud.githubusercontent.com/assets/156490/14620806/c20ff334-0573-11e6-82a3-ddb095d16c96.png)

![screen shot 2016-04-18 at 2 43 10 pm](https://cloud.githubusercontent.com/assets/156490/14620828/ea3a1164-0573-11e6-8736-228ad36d7d60.png)

**Comment by timrwood** [comment]
That error seems to be related to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions, can you check if you are calling `Object.preventExtensions` in your code?

**Comment by fricke** [comment]
We are not currently using that method anywhere in our code, but we are using an immutable data store in our application that feeds the params to this moment call.  If I stop the environment at the point where it's going to break at the application level, where we call moment, any call we make to moment.utc with a date formatter throws this error in the console.

**Comment by fricke** [comment]
What's really confusing here is that it's not complaining about inputs being extensible, it's just the ```this``` object is not extensible within moment itself.

**Comment by fricke** [comment]
the answer to this riddle was that we have an immutable store, baobab under the hood (wrapped w/ cerebral) and that store is immutable.  There was 1 place where a moment object was landing on the store where it was not suppose to be.  In doing that, it Object.freeze's the moment object, and any of it's children.  So, wrapping locale and the moment object on the prototype were effectively frozen.  This occurred in a totally separate area of the code base, but b/c it locked moment it locked it everywhere.
