### ISSUE TITLE
Link to "parsing guide" in Docs results in 404

### ISSUE THREAD

**Issue by mikemccaughan** [moment/momentjs.com#293]
In the Docs, there's a line like this:

> Strict parsing is frequently the best parsing option. For more information about choosing strict vs forgiving parsing, see the parsing guide.

The "parsing guide" text at the end is a link to "~/guides/#/parsing", which when clicked goes to http://momentjs.com/~/guides/#/parsing, which results in a 404. Looks like it should go to http://momentjs.com/guides/#/parsing/. Note the lack of a tilde and the ending slash.

**Comment by maggiepint** [comment]
Fixed in PR #296
