### ISSUE TITLE
Parsing/String-Format documentation error

### ISSUE THREAD

**Issue by avoliva** [moment/momentjs.com#295]
Similar issue to #280 

`w ww` should say `0..52`. Right now it's `1..53`. May want to double check the others just in case
Check [here](http://momentjs.com/docs/#/parsing/string-format/)

**Comment by maggiepint** [comment]
The week numbers index from 1. Did you somehow get a week 0? If so, how?

See week numbering in ISO8601, with the comparison to Gregorian calendar.
https://en.wikipedia.org/wiki/ISO_8601#Week_dates

See also:

```js
moment('2015-12-26').format('w')
"52"

moment('2015-12-27').format('w')
"1"
```
