### ISSUE TITLE
Incorrect moment.parseZone signature

### ISSUE THREAD

**Issue by Jokero** [moment/momentjs.com#327]
From docs http://momentjs.com/docs/#/parsing/parse-zone:

```
moment.parseZone(String)
...
Note: this method only works for a single string argument, not a string and format.
```

But I see in tests https://github.com/moment/moment/blob/develop/src/test/moment/zones.js#L429 that `parseZone` can take format and other arguments:

``` js
test('parse zone with more arguments', function (assert) {
    test.expectedDeprecations();
    var m;
    m = moment.parseZone('2013 01 01 05 -13:00', 'YYYY MM DD HH ZZ');
    assert.equal(m.format(), '2013-01-01T05:00:00-13:00', 'accept input and format');
    m = moment.parseZone('2013-01-01-13:00', 'YYYY MM DD ZZ', true);
    assert.equal(m.isValid(), false, 'accept input, format and strict flag');
    m = moment.parseZone('2013-01-01-13:00', ['DD MM YYYY ZZ', 'YYYY MM DD ZZ']);
    assert.equal(m.format(), '2013-01-01T00:00:00-13:00', 'accept input and array of formats');
});
```

**Comment by tiljanssen** [comment]
Also the use of parseZone without arguments on a moment object is not described:
`moment('2013-01-01T13:00+0200').parseZone().format('ZZ')` which returns 0200 in any timezone.

**Comment by sibennayak** [comment]
Should I open a PR to fix this?

**Comment by maggiepint** [comment]
You're welcome to.

**Comment by PaulinaStypinska** [comment]
This seems like a great first bug to fix. If no one is working on this, can I take a look?

**Comment by marwahaha** [comment]
@PaulinaStypinska Go for it! :-)

**Comment by PaulinaStypinska** [comment]
Thank you! Will report back.

**Comment by PaulinaStypinska** [comment]
I've created a PR with the fix.
