### ISSUE TITLE
moment(s).parseZone() not documented

### ISSUE THREAD

**Issue by tiljanssen** [moment/momentjs.com#333]
The option to use `moment('2013-01-01T13:00+0200').parseZone()` should be documented in the "manipulate" section of the documentation.

`moment('2013-01-01T13:00+0200').parseZone().format('HH:mm ZZ')` will result in `13:00 +0200` in any timezone.

**Comment by sibennayak** [comment]
Should I open a PR to fix this?

**Comment by icambron** [comment]
Closing in favor of #340
