### ISSUE TITLE
momentjs.com/docs doesn't have `window.moment` available

### ISSUE THREAD

**Issue by moredip** [moment/momentjs.com#334]
While reading the docs I opened up web tools on the page to experiment with `moment`, but it doesn't seem to be exposed. `window.moment` _is_ available on the homepage, but the `/docs` page doesn't seem to load `global.js`, which I think is where the homepage is getting `window.moment` from.

I'm happy to send a PR to fix this if you'd like. Pointers on where to make the change would be appreciated, but I'm happy to just poke around and figure it out.

**Comment by maggiepint** [comment]
I see this sometimes too, but it's intermittent. Haven't gotten around to troubleshooing it yet.

**Comment by akanshgulati** [comment]
@maggiepint  @moredip I tried to reproduce the issue on Chrome Version 71.0.3578.8. But could not find the issue now as supposedly this is fixed now.

**Comment by marwahaha** [comment]
I'm going to close it, and we can re-open if it comes up again.
