### ISSUE TITLE
Figure out why Travis is failing

### ISSUE THREAD

**Issue by maggiepint** [moment/momentjs.com#339]
Travis is failing, I think because it is attempting to do a deploy on pull request, which it shouldn't. The pull request task should just run the markdown tester. Have to figure this out.

**Comment by sibennayak** [comment]
Is it because travis.yml says `script: bash ./deploy.sh`?

**Comment by maggiepint** [comment]
Yes, it is. I just need to figure out what we want to do instead.

**Comment by sibennayak** [comment]
Maybe just this much?
```
# run our compile script
./compile.sh

# test that all of the documentation is runnable
npm run doctest
```

**Comment by maggiepint** [comment]
yes, but the deploy code needs to still run when we merge to master (it's a
continuous deploy process)

**Comment by butterflyhug** [comment]
Right-o.  I've done that before, will attempt a quick PR now.
