### ISSUE TITLE
Document locale as array in constructor functions

### ISSUE THREAD

**Issue by maggiepint** [moment/momentjs.com#343]
The documentation point out that [`moment.locale`](http://momentjs.com/docs/#/i18n/changing-locale/) may receive an array. However, other functions taking a local value are not documented as being able to receive an array. Although it works well: [jsfiddle](https://jsfiddle.net/t22krgLw/).

Therefore, I wonder if you are not missing the following definitions in your documentation and typescript declaration.

For [changing locales locally](http://momentjs.com/docs/#/i18n/instance-locale/), add

```
moment().locale(String[]);
```

For [string+format](http://momentjs.com/docs/#/parsing/string-format/), add

```
moment(String, String, String[], [Boolean]);
moment(String, String[], String[], [Boolean]);
```

For [utc](http://momentjs.com/docs/#/parsing/utc/), add

```
moment.utc(String, String, String[]);
```

**Comment by maggiepint** [comment]
This is a copy/pasted issue from somewhere. This functionality is undocumented, and I don't think the way it behaves is the way the user would expect. Right now what will happen if an array of locales is passed to a factory function, is that the first loaded locale will be chosen. Basically, it works exactly the same way that ``moment.locale([])`` does. 

I don't think that behavior is what the user would expect from a constructor function. I would think that the user would expect the parser to check all of the passed locales to see if the date is in that language, similar to the way multiple format parsing works. @icambron or @ichernev you don't happen to know the intent here do you?

**Comment by icambron** [comment]
I don't think it makes much sense for parsing, no. I think it's just an artifact of downstream locale processing being cool with arrays. I think we modified `getLocale` to deal with arrays and then called it from, `#locale` and `.locale`, and didn't really think of the consequences of calling it from [here](https://github.com/moment/moment/blob/800fba5bf0e8ad8f43219c859ef4a7fa486f4653/src/lib/create/from-anything.js#L34).
