### ISSUE TITLE
Short months and days in current locale without trailing period

### ISSUE THREAD

**Issue by Tklaversma** [moment/momentjs.com#350]
`moment.monthsShort()` returns an array of the months in short. But when the locale is for example Dutch, it will return an array of months in short **with a trailing period**.

How do I use `moment.monthsShort()` to get a list of the months in the current locale without any trailing dot (or any other character)?

The same goes for the days of the week.
`moment.weekdaysShort()` returns the days of the week in short in the current locale with a trailing period when the current local is Dutch.

The documentation said something about:
`moment.monthsShort('-MMM-')`
`moment.weekdaysShort('-DD-')`

But this isn't working...

Any idea? Hope you guys can help me out.

Regards,
TK

**Comment by Tklaversma** [comment]
Anyone?

**Comment by antonama** [comment]
Could you please move your question (if it is still relevant) to https://github.com/moment/moment/issues?
Or just close it here, whatever you prefer.

**Comment by Tklaversma** [comment]
Moved.
