### ISSUE TITLE
Getting time zone from moment is not documented

### ISSUE THREAD

**Issue by cmatteri** [moment/momentjs.com#353]
A moment's time zone can be accessed by calling its tz method with no arguments. Is this behavior supported? If so it should probably be documented.

**Comment by mnespor** [comment]
I discovered this functionality after seeing `moment.format is not a function` in a few unexpected places 😬

**Comment by mj1856** [comment]
```js
var m = moment.tz('America/Los_Angeles');
var z = m.tz();  // "America/Los_Angeles"
```
```js
var m = moment.tz('2017-01-01T00:00:00-08:00', 'America/Los_Angeles');
var z = m.tz();  // "America/Los_Angeles"
```

However,
```js
var m = moment();
var z = m.tz(); // undefined
```
```js
var m = moment.utc();
var z = m.tz(); // undefined
```
```js
var m = moment.parseZone('2017-01-01T00:00:00-08:00');
var z = m.tz(); // undefined
```

So yes, it will work, but only if the the original moment was constructed with `moment.tz`

**Comment by mnespor** [comment]
I see a couple of lines to that effect made it into b2747f3d95c378745dca5936ff70b63aa46565d4. Thanks! 😄 

I wasn't relying on this behavior; quite the opposite! I had a line `return expirationDate.tz(user.tz).format('MM/DD/YYYY');` that started to blow up after a change that made `user.tz` optional.

**Comment by mj1856** [comment]
Yep. Looks like #363 took care of this. 👍
