### ISSUE TITLE
Update docs WRT moment-timezone abbreviations

### ISSUE THREAD

**Issue by mj1856** [moment/momentjs.com#372]
Since the TZDB has started replacing made-up abbreviations with offsets, our documentation should be updated to reflect that the `z` formatting token doesn't always give you an abbreviation.

For example:

``` js
moment.tz('America/Los_Angeles').format('z') // "PDT"     (abbreviation)
moment.tz('Asia/Magadan').format('z')        // "+11"     (3-char offset)
moment.tz('Asia/Colombo').format('z')        // "+0530"   (5-char offset)
```

**Comment by spokzers** [comment]
Hi there,
Is this issue still open?
I'd like to contribute to it

PS: I am beginner so any guidance will be appreciated

Thanks

**Comment by marwahaha** [comment]
Sure @spokzers the docs can always use work. Probably, this section is a good place to update: http://momentjs.com/timezone/docs/#/using-timezones/formatting/

**Comment by spokzers** [comment]
great
I'll submit a PR soon

**Comment by maggiepint** [comment]
closing in favor of pull
