### ISSUE TITLE
When time is in UTC, moment is adding system time zone while moment is applied.

### ISSUE THREAD

**Issue by anujay88** [moment/momentjs.com#373]
When datetime is in UTC format and moment function is called on the datetime, system time zone is applied to the datetime. For example, if date is 28/10/2016 1:00 AM which is UTC date time and my computer system zone is in IST then when date is displayed it will be displayed as 28/10/2016 6:30 AM.

**Comment by maggiepint** [comment]
Yes. This is how moment works. You need to choose a different factory function. See this blog post:
https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/
