### ISSUE TITLE
Documentation is lacking duration.toISOString

### ISSUE THREAD

**Issue by michaelkrone** [moment/momentjs.com#376]
The duration part of the documentation is lacking documentation for the `toISOString` method

**Comment by antonama** [comment]
Now it has it http://momentjs.com/docs/#/displaying/as-iso-string/

**Comment by michaelkrone** [comment]
It still seems missing for the [durations section](http://momentjs.com/docs/#/durations/).

    moment.duration(1, 'd').toISOString() // "P1D"

**Comment by mitul45** [comment]
I can add this to docs. One question, how can I find from which version `toISOString()` was supported?

**Comment by marwahaha** [comment]
@mitul45 Check here https://github.com/moment/moment/blob/develop/CHANGELOG.md

**Comment by marwahaha** [comment]
This is done: http://momentjs.com/docs/#/durations/as-iso-string/
