### ISSUE TITLE
Add a comment about momentjs execution on browser consoles

### ISSUE THREAD

**Issue by shuheiktgw** [moment/momentjs.com#388]
### Proposal
Add a document that describes people can try momentjs on browser consoles in the document page.

### Why
It improves user experiences if they can know that it is possible to easily try momentjs on a console in document page without any installations.

### Solutions

For example add a description about a console at the beginning of the document that people can try momentjs on their browses consoles. 

### Screen shot

The console's execution screen shot below.

<img width="476" alt="2017-01-28 15 04 44" src="https://cloud.githubusercontent.com/assets/7028383/22394723/2b07e8a6-e56b-11e6-81ef-45edc8ae7d28.png">

**Comment by maggiepint** [comment]
sure.

**Comment by maggiepint** [comment]
Closed #389
