### ISSUE TITLE
how do i save date ( date object ) in the database in order to leverage momentjs ?

### ISSUE THREAD

**Issue by jpca999** [moment/momentjs.com#408]
one, of the big challenges that i have is, we have customers in differnt time zones, 
so the system shoudl work according to their saved tiems, if they wanna followup on somethign on March 18'2017 it shoudl be saved in such a way that it works for them. 

Secondly, we want to be able to cacluate the objects that has date stamped,  from a range of 3-1-17 to 3-15-17. 

Whats the best way to save dates in the database so that we coudl get the best benefit while serviing the customers globally ?

**Comment by marwahaha** [comment]
Hi @jpca999 

I recommend you check out [moment-timezone](http://momentjs.com/timezone/) to allow customers to work in different time zones. This will handle some parsing with respect to date formatting.

The [Duration objects](http://momentjs.com/docs/#/durations/) can help you calculate objects timestamped over a period of time.

This can be run [in Node.js or in the browser](http://momentjs.com/docs/#/use-it/). From there, you can write the objects to a database.

If this answers your questions, please close the issue!
