### ISSUE TITLE
Document moment.defaultFormatUtc

### ISSUE THREAD

**Issue by mj1856** [moment/momentjs.com#422]
We describe `moment.defaultFormat` [here](http://momentjs.com/docs/#default-format), but in 2.13.0 we also added `moment.defaultFormatUtc`, which is not documented.

See moment/moment@c593737 and moment/moment-timezone#447

**Comment by ramasCoder** [comment]
Is this still open ? Can I work on this ?

**Comment by icambron** [comment]
@ramasCoder Looks like there's a fix submitted for this already here: https://github.com/moment/momentjs.com/pull/430

**Comment by ramasCoder** [comment]
Thanks Isaac. I would like to contribute in whatever ways possible. Please
do let me know in case there is an opportunity.
