### ISSUE TITLE
Mistake in Documentation moment.utc().seconds(30)

### ISSUE THREAD

**Issue by usmandap** [moment/momentjs.com#447]
I found a small issue in moment js documentation. In documentation, if you see under heading of UTC it says `moment.utc().seconds(30) === new Date().setUTCSeconds(30);`, But `moment.utc().seconds(30)` returns an object while `new Date().setUTCSeconds(30);` returns milliseconds which is not equivalent to `new Date().setUTCSeconds(30);`. In that case it should be 
`moment.utc().seconds(30).valueOf() === new Date().setUTCSeconds(30);`

![screen shot 2017-09-14 at 1 54 54 pm](https://user-images.githubusercontent.com/15185299/30420851-578a2cfc-9954-11e7-9dab-4474bba2227e.png)
Please confirm it and let me know I'll make a PR for it soon.

**Comment by maggiepint** [comment]
Yeah, you're right that the documents aren't correct there. Feel free to submit PR

**Comment by usmandap** [comment]
Sure will be making a PR soon.

**Comment by usmandap** [comment]
Hi @maggiepint!
I've made a PR for it, above is the reference attached. Thanks
