### ISSUE TITLE
Docs, query, isSame

### ISSUE THREAD

**Issue by EgorEres** [moment/momentjs.com#450]
When test moment('same date').isSame('same Array', 'year or month or day or ...') return true if Array empty, it should be? When Array not empty, all ok.

**Comment by maggiepint** [comment]
I'm not sure if I understand your question. Can you show me an example with actual values?

**Comment by EgorEres** [comment]
moment(new Date()).isSame([], 'day') => true

**Comment by icambron** [comment]
When the array is empty, it returns the current time, which will (almost always) be the same day as the `new Date()` you just called
