### ISSUE TITLE
Remove all references to pre-2.0 Moment

### ISSUE THREAD

**Issue by icambron** [moment/momentjs.com#472]
There are all these little notes about differences in behavior that refer to now-ancient versions of Moment. I think we can alleviate the clutter by removing all the ones that refer to pre-2.0 Moment.

**Comment by jungleBadger** [comment]
Hi there! Looking into it.

**Comment by GregBorrelly** [comment]
Hello anyone working on this ?

**Comment by jungleBadger** [comment]
Hello @GregBorrelly : https://github.com/moment/momentjs.com/pull/475

**Comment by GregBorrelly** [comment]
@jungleBadger  thank you

**Comment by sourabh1031** [comment]
Hello i am newcomer and would like to work on this issue.Can you provide me some more help so that i can understand the issue more clearly?

**Comment by pcstyles** [comment]
![img_2444](https://user-images.githubusercontent.com/24754657/45936078-5ac1ff00-bf67-11e8-829b-ff46e3bf9d96.JPG)
![img_2443](https://user-images.githubusercontent.com/24754657/45936079-5ac1ff00-bf67-11e8-98bc-97dd13929b9e.JPG)
![img_2442](https://user-images.githubusercontent.com/24754657/45936080-5ac1ff00-bf67-11e8-88ca-14bcf30d0dbd.JPG)
![img_2440](https://user-images.githubusercontent.com/24754657/45936081-5ac1ff00-bf67-11e8-9a12-89040f5170c2.JPG)
![img_2431](https://user-images.githubusercontent.com/24754657/45936082-5ac1ff00-bf67-11e8-8031-c0da6c98c030.JPG)
![img_2429](https://user-images.githubusercontent.com/24754657/45936083-5b5a9580-bf67-11e8-9d47-59d28db2130f.JPG)
![img_2412](https://user-images.githubusercontent.com/24754657/45936084-5b5a9580-bf67-11e8-950c-98dd48692393.JPG)

**Comment by BrendanCarlin** [comment]
Hey everyone,
It looks like this effort was partially resolved with #475, but the changes requested by @marwahaha  were never implemented. #530 seeks to resolve this issue and include the pending updates requested in #475.

**Comment by nicktamburro** [comment]
Like this, for example? 

Found in docs>moment>01-parsing>02-string.md -

**Note:** Automatic cross browser ISO-8601 support was added in version **1.5.0**. Support for the week and ordinal formats was added in version **2.3.0**.

SHOULD BE:

**Note:** Support for the week and ordinal formats was added in version **2.3.0**.

**Comment by marwahaha** [comment]
fixed by https://github.com/moment/momentjs.com/pull/530
