### ISSUE TITLE
moment.format and toISOString() in locale='ar' don't return ISO8601 strings

### ISSUE THREAD

**Issue by eschiebel** [moment/momentjs.com#496]
Go to https://momentjs.com/
Scroll down to the Multiple Locale Support section and click on the 'ar' button
Notice that the example for `moment.format()` yields Arabic, not a valid ISO8601 ASCII string.
The same is true for `moment.toISOString()`

**Comment by ichernev** [comment]
Reported first in https://github.com/moment/moment/issues/4448

```javascript
> moment.locale('ar')
'ar'
> moment().toISOString()
'2018-06-28T07:52:28.812Z'
> moment().format()
'٢٠١٨-٠٦-٢٨T١٠:٥٢:٣٢+٠٣:٠٠'
```

I don't see how this is also a problem with `.toISOString()`.

**Comment by marwahaha** [comment]
Please re-open if you still have issues.
