### ISSUE TITLE
plugin for german holidays

### ISSUE THREAD

**Issue by DaniSchenk** [moment/momentjs.com#518]
I made a moment.js plugin to determine if a date is a german holiday. In germany, and other countries as well, it's a bit complicated to determine if a date is a holiday, because religious holidays vary every year and differ within 16 german states.
I know it's not generally suitable, but if you think a mention in the plugin section is useful, I will make a PR.
Repo: [https://github.com/DaniSchenk/moment-feiertage](https://github.com/DaniSchenk/moment-feiertage)

Regards ❤️

**Comment by marwahaha** [comment]
Sure! We'll take a PR in the plugins section.
