### ISSUE TITLE
Inconsistent local identifiers, eg. en-AU vs en-au

### ISSUE THREAD

**Issue by Jaans** [moment/momentjs.com#545]
On the documentation pages for internationalisation, locale identifiers use the common form of identifiers that capitalises the region part of the locale (when specified).

For example: en-**AU**, fr-**FR**
See here [momentjs Documentation](http://momentjs.com/docs/#/i18n/changing-locale/)
![image](https://user-images.githubusercontent.com/3510981/50258817-16061100-044d-11e9-8ec2-7a06e6ff2dce.png)

However, when I initially set the locale using the format "en-AU", it doesn't stick.
```
import moment from "moment";
import "moment/locale/en-au";
moment.locale("en-AU");
console.log(moment.locale()); // Result: **undefined**
```

But if I do it using all lowercase it works first time around:
```
import moment from "moment";
import "moment/locale/en-au";
moment.locale("en-au");
console.log(moment.locale()); // Result: "en-au"
```

Interestingly enough, if I initially set the locale to something that does stick and then set it "en-AU" it works:
```
import moment from "moment";
import "moment/locale/en-au";
moment.locale("en");
moment.locale("en-AU");
console.log(moment.locale()); // Result: "en-au" : now it works??
```

So that means:
- If the format is such that the region portion is in capitals, e.g. "en-AU", then there is a bug if you set the locale using this format first up.
- If the format is meant to be all lower case "en-au", then the documentation is using the wrong format.

Thanks

**Comment by marwahaha** [comment]
Thanks for opening this request.
Hi! Thanks for filing this issue! Unfortunately, I can't reproduce this. Could you provide any other information?

```
moment.locale() // "en"
moment.locale("en-AU"); // "en-au"
moment.locale() // "en-au"
```
