### ISSUE TITLE
Document "ignoreCache" argument of moment.tz.guess()

### ISSUE THREAD

**Issue by VSchlattinger** [moment/momentjs.com#550]
The documentation doesn't say anything about the "ignoreCache" argument in the `guess()` function. I just wasted a lot of development time on figuring out why my App stays stuck on the same timezone until I reload it completely. Only after digging through the code itself, I found out that the detected timezone is cached and won't change unless I call `moment.tz.guess(true)` instead of just `moment.tz.guess()`.

Please add this argument to the documentation and maybe also add a hint that the timezone is cached by default if no argument is passed.

If you want, I can create a PR for this.

**Comment by marwahaha** [comment]
Sure, go for it!

**Comment by VSchlattinger** [comment]
OK, here is the PR: https://github.com/moment/momentjs.com/pull/552

Let me know, if I should change something.
