### ISSUE TITLE
If I create a PR with some small changes, will it get merged?

### ISSUE THREAD

**Issue by Laoujin** [moment/momentjs.com#573]
I'm creating a blog post on Moment.js and am noticing the docs are slightly out of sync here and there.

ex: Describing function parameters with `moment-like` vs `Moment|String|Number|Date|Array`  
--> "Object" is missing in both

If I create a PR, will it ever get merged? :) 
I'm asking because some PRs are open since 2017...

**Comment by lkreimann** [comment]
I don't see why it shouldn't get merged (I'm no maintainer etc. though). Chunk your changes into logical bits (PRs/commits) would be the best, but if it's just missing types, one PR would probably be enough. 
Look at older PRs and the responses on these to get a feeling for the responses that you could get for your PR :slightly_smiling_face:

**Comment by marwahaha** [comment]
Sure, I'll do my best to review and merge it.
