### ISSUE TITLE
Missing SECURITY.md

### ISSUE THREAD

**Issue by OtacilioN** [moment/momentjs.com#580]
**Feature requested**

GitHub has just released the Security Policy feature, by writing the SECURITY.md file a new tab with security informations should appear in the repository.

You can check the [Electron SECURITY.md example](https://github.com/electron/electron/blob/master/SECURITY.md)

It will really improve people trusting in open source security standards.

I can help to write these file if you want folks, what do you think?

**Comment by OS-the-Person** [comment]
Could I help with this?

**Comment by marwahaha** [comment]
What would we add here?

**Comment by OtacilioN** [comment]
Hey @marwahaha I can propose a structure and you folks can fill the information and decide what to use or not.

**Comment by marwahaha** [comment]
Sure. I'm not sure what additional things the Moment.js maintainers can do if there is a security issue.

**Comment by OtacilioN** [comment]
The first thing is to get know what vulnerabilities people reported than maintainers can decide if they will scale first to an internal team of maintainers and most active contributors, where they can trust depending on the level of vulnerability, or if they can just open an issue or discussion asking the community to solve it.

**Comment by marwahaha** [comment]
I think the community should handle it.
I don't think this would function differently than a usual issue or feature request.
This is why I am unsure we need a SECURITY.md file.

**Comment by OtacilioN** [comment]
Yeah, but remember that Moment.js is a dependency of many repositories if someone discovers a vulnerability, maybe opening a public issue on GitHub is not the best way to report the vulnerability. 

Attackers will get notified about this security issue before the community will have time to handle and fix it.

**Comment by OtacilioN** [comment]
I opened a pull request, so you folks can see my structure proposal and think about it. The first security policy doesn't need to be the best, but it can start community discussions about security.
