### ISSUE TITLE
DST Santiago Chile wrong date

### ISSUE THREAD

**Issue by webmedia7** [moment/momentjs.com#593]
Hi guys,

there is a new law according to which the DST should happen on September 8th and not on 8th of August (https://www.timeanddate.com/time/change/chile/santiago). Is there going to be a quick fix for this or we have to somehow patch it with out own logic? 

Thanks for your reply in advance!

Cheers
Boyan

**Comment by ODAVING** [comment]
I can fix this issue

**Comment by marwahaha** [comment]
Is this still an issue?
Please re-open if you still have issues.
Perhaps your usage was incorrect: https://momentjs.com/docs/#/parsing/object/
> Note that like moment(Array) and new Date(year, month, date), months are 0 indexed.
