### ISSUE TITLE
Scrimba Took Down the Moment Course?

### ISSUE THREAD

**Issue by YosefLehrer** [moment/momentjs.com#609]
I remember seeing the MomentJS course up on Scrimba about 2 months ago, now I'm just getting started with MomentJS and I clicked the link from the [guide](https://momentjs.com/guides/) section that should take me to this [Scrimba course](https://scrimba.com/casts/cwpDGhG) but it's pretty much gone, it's just one page that has no video or playlist.

**Comment by marwahaha** [comment]
Sorry, I  don't know much about Scrimba. Perhaps there are other tutorials online. 
We have some examples in https://momentjs.com/docs/ .
Best of luck!

**Comment by YosefLehrer** [comment]
The reason why I opened this is that it is on the docs. If Scrimba doesn't have the course anymore there shouldn't be a link.
But it seems that the course is back up.
