### ISSUE TITLE
Documentation contains incorrect types/arguments for strict-nulls in Typescript.

### ISSUE THREAD

**Issue by pnappa** [moment/momentjs.com#619]
Hi,

I run Typescript with strict nulls enabled, and I experience an issue when calling `isBetween(start, end, units, inclusion)`, when providing `units` as `null` as per the documentation. As the type definitions indicate units is an optional parameter, the correct value in the documentation should actually be `undefined`. Realistically, this isn't going to be the only instance of this problem. 

It's probably wiser to make a pull request when we have slightly more signatures to update in the documentation, as this is likely a problem for all optional parameter examples in the docs.

Cheers

**Comment by marwahaha** [comment]
Hi,
Thanks for the comment.
I think this is an issue only for isBetween. I'll submit a PR now.
