### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by anno1985** [moment/momentjs.com#661]
The URL behind the `Read` link added in https://github.com/moment/momentjs.com/commit/130f4f6b053ff0bff491faabc6531573e06abfd1 returns a 404 for me.

**Comment by marwahaha** [comment]
Thanks. I'll update with a different link.

**Comment by marwahaha** [comment]
fixed in https://github.com/moment/momentjs.com/commit/6b4bf0da8b3597be060badd528d6df6ca521d7dc
