### ISSUE TITLE
Not sure how to build

### ISSUE THREAD

**Issue by icambron** [moment/momentjs.com#67]
If I do a `clone --recurisve` on this, then run `npm install`, I should be able to just run `grunt` to build, right? However, I get this:

```
isaac@ironhide [07:10:42] [~/code/momentjs.com] [gh-pages]
-> % grunt
Loading "html.js" tasks...ERROR
>> Error: Cannot find module 'moment'
Warning: Task "html" not found. Use --force to continue.

Aborted due to warnings.
```

Not sure what to do.

**Comment by malashkevich** [comment]
Hey guys.
Sorry for necroposting but I need your assistance.
I'm working mostly in mobile development so I'm not very familiar with web technologies however I love moment.js and want to help a bit.
Can you pls explain how to update documentation?
I was able to run it but after idk how to recompile it in correct way. Obvious for me commands like `grunt clean & grunt html` do not give expected effect.
So it will be perfect if you describe a bit this process. 
Thanks.
