### ISSUE TITLE
Improve accessibility color contrast of BLM banner.

### ISSUE THREAD

**Issue by karnett** [moment/momentjs.com#673]
**Describe the bug**
The current blue against the background fails contrast guidelines at 2.59:1

AA compliance requires at least 4.5:1
Moving up the lightness scale recommends #6782DA, if you don't have something that fits within your color palette.
Thanks for all the work you do.

**To Reproduce**
1. Go to https://momentjs.com
2. Observe color of blue links against dark background.

**Expected behavior**
Links within the BLM banner should meet accessibility standard of 4.5:1 contrast.

**Screenshots**
Via: https://webaim.org/resources/contrastchecker/
<img width="716" alt="Screen Shot 2020-08-21 at 10 15 04 AM" src="https://user-images.githubusercontent.com/8050467/90900768-e6cd4300-e397-11ea-8e54-163d2d7e8ab0.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version 13.1.2

**Comment by marwahaha** [comment]
Hi @karnett  ! Thanks for reporting this. This is an important thing to consider, so thanks for the webaim link also.

 I took your suggestion on the color.

Cheers!
