### ISSUE TITLE
Request Project Status Authorization

### ISSUE THREAD

**Issue by QC-L** [moment/momentjs.com#680]
Hey guys. I'm from China and I really like Moment.js. I tried to translate the project status of moment.js, can I ask you for an exclusive license in China?

[Project Status](https://momentjs.com/docs/#/-project-status/)

**Comment by marwahaha** [comment]
Sorry, I don't understand what you are looking for.

**Comment by QC-L** [comment]
I want to get authorization for this article.

**Comment by mj1856** [comment]
If you are asking if you can translate the project status text to Chinese and post it on a separate web site - yes.  That is OK.  However, please include a link back to our official English statement and a note that you are posting a translation.

If you are asking for an "exclusive" - no. Anyone can post such a translation.  We would not limit it to a single individual or organization.
