### ISSUE TITLE
[Docs] Adding multi language support to documentation

### ISSUE THREAD

**Issue by shawnscoding** [moment/momentjs.com#683]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I am wondering if you have thought of adding Korean documentation for the users who don't understand English well. 
I have seen my colleagues having a difficult time understanding moment js because the documentation is written in English which they are not fluent in.
I would like to help with the Korean translation. :) 

If you allow me to do the work, I am going to translate the documentation only what it says. No modification or adding new stuff. :)

**Comment by marwahaha** [comment]
Sure, if you'd like to transfer the documentation I can post a link to it. Or if there is a way to auto-translate the site, that works too.

**Comment by shawnscoding** [comment]
Hi. I am really happy to hear that. Thank you for the opportunity.
There is one problem though.
I cloned moment.com repository ( https://github.com/moment/momentjs.com )
from Github to start off translating the documentation. website. However, I
failed to run this project locally. It is quite complicated for me.
I think I will need to be able to run the program to translate the language
and test it before publishing so that I can give you the link.
I am hoping that you could give me the guidelines on how to run this
project and test it.
Thank you !!

**Comment by marwahaha** [comment]
Sorry you're having a problem. Try running `grunt server`.

https://github.com/moment/momentjs.com#running-locally

**Comment by marwahaha** [comment]
This may also help: https://github.com/moment/moment/blob/develop/CONTRIBUTING.md#setting-up-development-environment

**Comment by marwahaha** [comment]
If you still need help, please re-open this issue.
