### ISSUE TITLE
[Docs] Adding multi language support to documentation

### ISSUE THREAD

**Issue by shawnscoding** [moment/momentjs.com#687]
Hi. I created this issue 
https://github.com/moment/momentjs.com/issues/683
I still can not run the site locally.

I tried with two methods that you suggested 
https://github.com/moment/momentjs.com#running-locally
https://github.com/moment/moment/blob/develop/CONTRIBUTING.md#setting-up-development-environment
but still no luck.

I installed  grunt -g and node_modules like this
```
npm install -g grunt-cli
npm install
```
When I run grunt server 
The error said 
>> Error: Cannot find module '../libs/moment'
>> Require stack:
>> - /Users/shawn/Documents/projects/momentjs.com-in-korean/data/size.js
>> - /Users/shawn/Documents/projects/momentjs.com-in-korean/tasks/html.js
>> - /Users/shawn/Documents/projects/momentjs.com-in-korean/node_modules/grunt/lib/grunt/task.js
>> - /Users/shawn/Documents/projects/momentjs.com-in-korean/node_modules/grunt/lib/grunt.js
>> - /usr/local/lib/node_modules/grunt-cli/bin/grunt

My machine is Macbook pro
version 10.15.6

Do you have any idea ? 
Thanks!!

**Comment by marwahaha** [comment]
Sorry you are still having issues. [Try running](https://github.com/moment/momentjs.com#installing---linuxunix)
```
./compile.sh
```
