### ISSUE TITLE
isSameOrAfter does not work with hours and minutes

### ISSUE THREAD

**Issue by codewithpatelo** [moment/momentjs.com#707]
moment('20:15:00').isSameOrAfter('17:15:00'));

result --> false

Why?

**Comment by marwahaha** [comment]
Hi @codewithpatelo - With your inputs you must specify a format. Otherwise the behavior may be very strange.

See more information here. https://momentjs.com/docs/#/parsing/string-format/

Hope this answers your question!

> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged.
