### ISSUE TITLE
Support Ukraine?

### ISSUE THREAD

**Issue by ellenaua** [moment/momentjs.com#720]
Guys, currently there is a banner "Black lives matter" on the main page.
Maybe, we can show support for Ukraine and show banner "Ukrainian lives matter"?
Or you want to stay aside from politics? (I will understand it)

**Comment by mattjohnsonpint** [comment]
I am in favor of this.  A PR would be nice.

**Comment by emmanuelvlad** [comment]
You could also add:
- Climate change
- Hunger
- Equality
- Minorities right
- Income gap
- Maybe a video of your favourite politic

Because people really need to see that when they are working.

**Comment by aentwist** [comment]
This is a piece of code. Political views should be removed.

If you decide not to remove the political views, I would encourage you to add more information about BLM to make it clear on what is being supported.

From the organization's "Demands" page,

> 5. Defund the police

> the Domestic Terrorism Prevention Act of 2021 [is] used to target Black and brown communities for heightened surveillance

https://blacklivesmatter.com/blm-demands/

**Comment by missile-xuan** [comment]
This is a piece of code. Political views should be removed. +1

**Comment by AndrewDavis** [comment]
Black Ukrainians Matter

**Comment by snowman** [comment]
All Lives Matter

**Comment by snowman** [comment]
Yellow lives matter

**Comment by AndrewDavis** [comment]
No Lives Matter

You're all meaningless, worthless scum; now get back to coding!!!
