### ISSUE TITLE
Links from Moment docs to Luxon docs broken

### ISSUE THREAD

**Issue by mikebeaton** [moment/momentjs.com#726]
A few links from Moment docs to Luxon docs are currently broken (presumably because of Luxon doc layout update at some point), as follows:

 - https://moment.github.io/luxon/docs/manual/why.html should be https://moment.github.io/luxon/#/why
 - https://moment.github.io/luxon/docs/manual/moment.html should be https://moment.github.io/luxon/#/moment
 - https://moment.github.io/luxon/docs/manual/matrix.html should be https://moment.github.io/luxon/#/matrix

Fixed by #725.

**Comment by verhovsky** [comment]
A lot of people have tried to fix it

https://github.com/moment/momentjs.com/pulls?q=is%3Apr+luxon+

**Comment by gilmoreorless** [comment]
#725 has now been merged and deployed.
