### ISSUE TITLE
Test reporting on IE8

### ISSUE THREAD

**Issue by mj1856** [moment/momentjs.com#74]
Running tests on IE8 goes really slow, but it works... right up to the end when all tests are done.

The test page tries to call `console.log`, which doesn't exist on IE8.

In order to build the buttons for submitting the test failure, you have to first shim the console.log function to do nothing (see http://stackoverflow.com/a/5967632/634824).  Otherwise, it just fails with a scripting error and you can't submit the bug report.

**Comment by mj1856** [comment]
As much as it pains me to say it in 2016, there will probably still be those that need IE8 support, so we should at least be able to run the test suite without it choking.  Marking up-for-grabs.

**Comment by victorzchan** [comment]
This should be closed with https://github.com/moment/momentjs.com/pull/451

**Comment by maggiepint** [comment]
closing unless we see a reason to re-open
