### ISSUE TITLE
Wrong UTF characters in two JS files distributed with WP or WP plugins

### ISSUE THREAD

**Issue by CaptainTomBln** [moment/momentjs.com#763]
Hi there, I am running three WP websites and I have to deal with many hacker attacks, So I installed the Anti-Malware plugin that works properly. But there are two files that cannot be scanned: /wp-includes/js/dist/date.js and /wp-includes/js/dist/date.min.js. Both seem to be part of the momentjs functionality. Also my editor PSPad doesn't load them, complaining that there are some wrong UTF characters included into the files. This is the same with all three WP websites. Using MS Word and saving the files again with the option "allow changing characters" I could make them readable by my editor as well as by the anti-malware scanner. But I am not sure if I didn't change anything important in those huge resources. Also I guess that WP updates will put the old files back on my WP installations. Does anybody have an idea how the files can be repaired and distributed to WP?
Thanks in advance, Thomas

**Comment by gilmoreorless** [comment]
Resolved at https://github.com/moment/moment-timezone/issues/1065
